# openapi2-functions.yaml
swagger: '2.0'
info:
  title: testdeletlater
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://test-delete-later-37120935558.us-central1.run.app
      responses:
        '200':
          description: A successful response
          schema:
            type: string